### ISSUE TITLE
Flixanity not working on Kodi 16.1 Jarvis

### ISSUE THREAD

**Issue by Robbie8592** [sClarkeIsBack/StreamHub#4]
This is what the log shows. 

20:47:24 T:3960   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.flixanity\default.py", line 271, in <module>
                                                index(url)
                                              File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.flixanity\default.py", line 46, in index
                                                all  = regex_get_all(open,'<section class="cardBox.+?flip">','</section>')
                                              File "C:\Users\AppData\Roaming\Kodi\addons\plugin.video.flixanity\default.py", line 184, in regex_get_all
                                                r = re.findall("(?i)(" + start_with + "[\S\s]+?" + end_with + ")", text)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\re.py", line 177, in findall
                                                return _compile(pattern, flags).findall(string)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--

**Comment by sClarkeIsBack** [comment]
This is because the site is using HTTPS encryption, Kodi 16.1 doesn't support this.
